---
env_vars:
  pass: otus2024

- name: PAM
  hosts: all
  become: yes
 
  tasks:
  - name: create group
    group:
      name: admin
      state: present

  - name: Create adm User
    user:
      name: otusadm
      create_home: yes
      uid: 1040
      password: "{{pass | password_hash('sha512')}}"
      group: admin
      shell: /bin/bash
      state: present

  - name: Create User
    user:
      name: otus
      create_home: yes
      uid: 1041
      password: "{{pass | password_hash('sha512')}}"
      shell: /bin/bash
      state: present